### ISSUE TITLE
Problems from within virtualenv

### ISSUE THREAD

**Issue by iwootten** [pyblish/pyblish-standalone#14]
When executing:

    python -m pyblish_standalone --debug --register-gui pyblish_lite

Within a virtual environment, the PySide interface briefly appears before disappearing, with the following message:

    Starting new QApplication..
    Installed opensans\OpenSans-Regular.ttf
    Installed opensans\OpenSans-Semibold.ttf
    Installed fontawesome\fontawesome-webfont.ttf
    About to reset..
    usage: __main__.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: __main__.py --help [cmd1 cmd2 ...]
       or: __main__.py --help-commands
       or: __main__.py cmd --help

     error: option --register-gui not recognized

When executing (from a separate venv):

    python -m pyblish_standalone --debug --register-gui pyblish_qml

I get:

    Found gui: <module 'pyblish_qml' from 'c:\Users\ian.wootten\Envs\pyblish-tester\lib\site-packages\pyblish_qml\__init__.pyc'>
    QWidget: Must construct a QApplication before a QWidget

**Comment by iwootten** [comment]
It looks to me the reason this is failing is down to the gui library interpreting the arguments supplied to standalone.

For reference, here's my requirements.txt:

```
appdirs==1.4.3
invoke==0.16.3
packaging==16.8
pbr==3.0.0
pyblish-base==1.4.4
pyblish-lite==0.7.4
pyparsing==2.2.0
PySide==1.2.4
six==1.10.0
stevedore==1.21.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper-win==1.2.1
```

**Comment by mottosso** [comment]
Thanks @iwootten, you can launch Pyblish Lite and QML without pyblish-standalone, like this.

```bash
$ python -m pyblish_lite --debug
$ python -m pyblish_qml --demo
```

**Comment by mottosso** [comment]
@tokejepsen is still project still needed?

**Comment by iwootten** [comment]
Ah right, ok - is this stale then? I was under the misapprehension this would be necessary to get started creating some unit/integration tests for our pyblish plugins.

**Comment by mottosso** [comment]
No need for GUIs when testing plug-ins, see the [`pyblish.util`](https://api.pyblish.com/pages/util.publish.html) module along with our [recent conversation on Gitter](https://gitter.im/pyblish/pyblish?at=590b250a4098d96d3436f770).

**Comment by tokejepsen** [comment]
Hey, this project is being used on the upcoming after effects integration: https://github.com/pyblish/pyblish-aftereffects/pull/1

You could quite possibly not use this project for after effects.
