### ISSUE TITLE
Implement argparse

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-standalone#3]
About [`__main__.py`](https://github.com/pyblish/pyblish-standalone/blob/34a943709d954b8d60be9333592633e19d16a496/pyblish_standalone/__main__.py).

[argparse](https://docs.python.org/2/library/argparse.html) could greatly simplify parsing of command line flags.

Have a look at Pyblish RPC's [`__main__.py`](https://github.com/pyblish/pyblish-rpc/blob/master/pyblish_rpc/__main__.py) for an example.

**Comment by mottosso** [comment]
Ping @tokejepsen

**Comment by tokejepsen** [comment]
I agree:) But couldn't figure it out while hacking it together.
